[2024-01-16T16:29:14.029+0200] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: executing_sql_pipeline.insertion_2 manual__2024-01-16T14:29:06.705753+00:00 [queued]>
[2024-01-16T16:29:14.034+0200] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: executing_sql_pipeline.insertion_2 manual__2024-01-16T14:29:06.705753+00:00 [queued]>
[2024-01-16T16:29:14.035+0200] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2024-01-16T16:29:14.068+0200] {taskinstance.py:2192} INFO - Executing <Task(SqliteOperator): insertion_2> on 2024-01-16 14:29:06.705753+00:00
[2024-01-16T16:29:14.073+0200] {standard_task_runner.py:60} INFO - Started process 49786 to run task
[2024-01-16T16:29:14.079+0200] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'executing_sql_pipeline', 'insertion_2', 'manual__2024-01-16T14:29:06.705753+00:00', '--job-id', '130', '--raw', '--subdir', 'DAGS_FOLDER/sqlite_pipeline.py', '--cfg-path', '/tmp/tmpdl3w2jc1']
[2024-01-16T16:29:14.082+0200] {standard_task_runner.py:88} INFO - Job 130: Subtask insertion_2
[2024-01-16T16:29:14.148+0200] {task_command.py:423} INFO - Running <TaskInstance: executing_sql_pipeline.insertion_2 manual__2024-01-16T14:29:06.705753+00:00 [running]> on host DESKTOP-9NHC01K.
[2024-01-16T16:29:14.254+0200] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='executing_sql_pipeline' AIRFLOW_CTX_TASK_ID='insertion_2' AIRFLOW_CTX_EXECUTION_DATE='2024-01-16T14:29:06.705753+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-16T14:29:06.705753+00:00'
[2024-01-16T16:29:14.256+0200] {sql.py:276} INFO - Executing: 
            INSERT INTO users (name, age) VALUES 
                ('Harry', 49),
                ('Nancy', 52),
                ('Elvis', 26),
                ('Mia', 20);
        
[2024-01-16T16:29:14.265+0200] {base.py:83} INFO - Using connection ID 'my_sqlite_cnn' for task execution.
[2024-01-16T16:29:14.286+0200] {base.py:83} INFO - Using connection ID 'my_sqlite_cnn' for task execution.
[2024-01-16T16:29:14.287+0200] {sql.py:450} INFO - Running statement: 
            INSERT INTO users (name, age) VALUES 
                ('Harry', 49),
                ('Nancy', 52),
                ('Elvis', 26),
                ('Mia', 20);
        , parameters: None
[2024-01-16T16:29:14.287+0200] {sql.py:459} INFO - Rows affected: 4
[2024-01-16T16:29:14.298+0200] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=executing_sql_pipeline, task_id=insertion_2, execution_date=20240116T142906, start_date=20240116T142914, end_date=20240116T142914
[2024-01-16T16:29:14.332+0200] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-01-16T16:29:14.361+0200] {taskinstance.py:3281} INFO - 1 downstream tasks scheduled from follow-on schedule check
