[2024-01-23T18:14:33.455+0200] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_to_redshift.create_table_in_redshift manual__2024-01-23T16:14:31.436463+00:00 [queued]>
[2024-01-23T18:14:33.462+0200] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_to_redshift.create_table_in_redshift manual__2024-01-23T16:14:31.436463+00:00 [queued]>
[2024-01-23T18:14:33.462+0200] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2024-01-23T18:14:33.549+0200] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): create_table_in_redshift> on 2024-01-23 16:14:31.436463+00:00
[2024-01-23T18:14:33.551+0200] {standard_task_runner.py:60} INFO - Started process 54662 to run task
[2024-01-23T18:14:33.556+0200] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'postgres_to_redshift', 'create_table_in_redshift', 'manual__2024-01-23T16:14:31.436463+00:00', '--job-id', '293', '--raw', '--subdir', 'DAGS_FOLDER/postgres_to_redshift.py', '--cfg-path', '/tmp/tmpf3w5f8cv']
[2024-01-23T18:14:33.558+0200] {standard_task_runner.py:88} INFO - Job 293: Subtask create_table_in_redshift
[2024-01-23T18:14:33.600+0200] {task_command.py:423} INFO - Running <TaskInstance: postgres_to_redshift.create_table_in_redshift manual__2024-01-23T16:14:31.436463+00:00 [running]> on host DESKTOP-9NHC01K.
[2024-01-23T18:14:33.681+0200] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='postgres_to_redshift' AIRFLOW_CTX_TASK_ID='create_table_in_redshift' AIRFLOW_CTX_EXECUTION_DATE='2024-01-23T16:14:31.436463+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-23T16:14:31.436463+00:00'
[2024-01-23T18:14:35.280+0200] {python.py:201} INFO - Done. Returned value was: None
[2024-01-23T18:14:35.289+0200] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=postgres_to_redshift, task_id=create_table_in_redshift, execution_date=20240123T161431, start_date=20240123T161433, end_date=20240123T161435
[2024-01-23T18:14:35.341+0200] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-01-23T18:14:35.358+0200] {taskinstance.py:3281} INFO - 1 downstream tasks scheduled from follow-on schedule check
