[2024-01-16T16:27:23.893+0200] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: executing_sql_pipeline.insertion_2 manual__2024-01-16T14:27:16.895581+00:00 [queued]>
[2024-01-16T16:27:23.898+0200] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: executing_sql_pipeline.insertion_2 manual__2024-01-16T14:27:16.895581+00:00 [queued]>
[2024-01-16T16:27:23.898+0200] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2024-01-16T16:27:23.917+0200] {taskinstance.py:2192} INFO - Executing <Task(SqliteOperator): insertion_2> on 2024-01-16 14:27:16.895581+00:00
[2024-01-16T16:27:23.919+0200] {standard_task_runner.py:60} INFO - Started process 49417 to run task
[2024-01-16T16:27:23.923+0200] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'executing_sql_pipeline', 'insertion_2', 'manual__2024-01-16T14:27:16.895581+00:00', '--job-id', '127', '--raw', '--subdir', 'DAGS_FOLDER/sqlite_pipeline.py', '--cfg-path', '/tmp/tmpvr_23z97']
[2024-01-16T16:27:23.924+0200] {standard_task_runner.py:88} INFO - Job 127: Subtask insertion_2
[2024-01-16T16:27:23.965+0200] {task_command.py:423} INFO - Running <TaskInstance: executing_sql_pipeline.insertion_2 manual__2024-01-16T14:27:16.895581+00:00 [running]> on host DESKTOP-9NHC01K.
[2024-01-16T16:27:24.032+0200] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='executing_sql_pipeline' AIRFLOW_CTX_TASK_ID='insertion_2' AIRFLOW_CTX_EXECUTION_DATE='2024-01-16T14:27:16.895581+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-16T14:27:16.895581+00:00'
[2024-01-16T16:27:24.032+0200] {sql.py:276} INFO - Executing: 
        INSERT INTO users (name, age) VALUES 
                ('Harry', 49),
                ('Nancy', 52),
                ('Elvis', 26),
                ('Mia', 20);
        
[2024-01-16T16:27:24.036+0200] {base.py:83} INFO - Using connection ID 'my_sqlite_cnn' for task execution.
[2024-01-16T16:27:24.050+0200] {base.py:83} INFO - Using connection ID 'my_sqlite_cnn' for task execution.
[2024-01-16T16:27:24.051+0200] {sql.py:450} INFO - Running statement: 
        INSERT INTO users (name, age) VALUES 
                ('Harry', 49),
                ('Nancy', 52),
                ('Elvis', 26),
                ('Mia', 20);
        , parameters: None
[2024-01-16T16:27:24.051+0200] {sql.py:459} INFO - Rows affected: 4
[2024-01-16T16:27:24.061+0200] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=executing_sql_pipeline, task_id=insertion_2, execution_date=20240116T142716, start_date=20240116T142723, end_date=20240116T142724
[2024-01-16T16:27:24.095+0200] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-01-16T16:27:24.132+0200] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
