[2024-01-18T13:03:33.782+0200] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: transformation_with_task_flow_api.group_by_region_smokers manual__2024-01-18T11:03:26.061570+00:00 [queued]>
[2024-01-18T13:03:33.787+0200] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: transformation_with_task_flow_api.group_by_region_smokers manual__2024-01-18T11:03:26.061570+00:00 [queued]>
[2024-01-18T13:03:33.788+0200] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2024-01-18T13:03:33.806+0200] {taskinstance.py:2192} INFO - Executing <Task(_PythonDecoratedOperator): group_by_region_smokers> on 2024-01-18 11:03:26.061570+00:00
[2024-01-18T13:03:33.809+0200] {standard_task_runner.py:60} INFO - Started process 22848 to run task
[2024-01-18T13:03:33.811+0200] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'transformation_with_task_flow_api', 'group_by_region_smokers', 'manual__2024-01-18T11:03:26.061570+00:00', '--job-id', '208', '--raw', '--subdir', 'DAGS_FOLDER/applying_task_flow_api.py', '--cfg-path', '/tmp/tmpme6z7yy7']
[2024-01-18T13:03:33.812+0200] {standard_task_runner.py:88} INFO - Job 208: Subtask group_by_region_smokers
[2024-01-18T13:03:33.843+0200] {task_command.py:423} INFO - Running <TaskInstance: transformation_with_task_flow_api.group_by_region_smokers manual__2024-01-18T11:03:26.061570+00:00 [running]> on host DESKTOP-9NHC01K.
[2024-01-18T13:03:33.947+0200] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='transformation_with_task_flow_api' AIRFLOW_CTX_TASK_ID='group_by_region_smokers' AIRFLOW_CTX_EXECUTION_DATE='2024-01-18T11:03:26.061570+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-18T11:03:26.061570+00:00'
[2024-01-18T13:03:33.949+0200] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/mahmoud/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/mahmoud/airflow_env/lib/python3.10/site-packages/airflow/decorators/base.py", line 242, in execute
    return_value = super().execute(context)
  File "/home/mahmoud/airflow_env/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/mahmoud/airflow_env/lib/python3.10/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/mahmoud/airflow/dags/applying_task_flow_api.py", line 39, in group_by_region_smokers
    df=pd.read_json(data)
  File "/home/mahmoud/airflow_env/lib/python3.10/site-packages/pandas/io/json/_json.py", line 780, in read_json
    json_reader = JsonReader(
  File "/home/mahmoud/airflow_env/lib/python3.10/site-packages/pandas/io/json/_json.py", line 893, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/mahmoud/airflow_env/lib/python3.10/site-packages/pandas/io/json/_json.py", line 933, in _get_data_from_filepath
    self.handles = get_handle(
  File "/home/mahmoud/airflow_env/lib/python3.10/site-packages/pandas/io/common.py", line 709, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/home/mahmoud/airflow_env/lib/python3.10/site-packages/pandas/io/common.py", line 1171, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
[2024-01-18T13:03:33.952+0200] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=transformation_with_task_flow_api, task_id=group_by_region_smokers, execution_date=20240118T110326, start_date=20240118T110333, end_date=20240118T110333
[2024-01-18T13:03:33.967+0200] {standard_task_runner.py:107} ERROR - Failed to execute job 208 for task group_by_region_smokers (argument of type 'method' is not iterable; 22848)
[2024-01-18T13:03:33.984+0200] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-01-18T13:03:33.993+0200] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
